# Generated by Django 5.1.5 on 2025-10-07 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DRCYYDL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(db_column='时间', null=True, unique=True, verbose_name='时间')),
                ('comm', models.CharField(db_column='通讯状态', max_length=8, verbose_name='通讯状态')),
                ('yzgw', models.FloatField(blank=True, db_column='一总供温', null=True, verbose_name='一总供温')),
                ('yzhw', models.FloatField(blank=True, db_column='一总回温', null=True, verbose_name='一总回温')),
                ('ywwc', models.FloatField(blank=True, db_column='一网温差', null=True, verbose_name='一网温差')),
                ('ygyl', models.FloatField(blank=True, db_column='一供压力', null=True, verbose_name='一供压力')),
                ('ygyllh', models.FloatField(blank=True, db_column='一供压(滤后)', null=True, verbose_name='一供压(滤后)')),
                ('yhyl', models.FloatField(blank=True, db_column='一回压力', null=True, verbose_name='一回压力')),
                ('ywyc', models.FloatField(blank=True, db_column='一网压差', null=True, verbose_name='一网压差')),
                ('swwd', models.FloatField(blank=True, db_column='室外温度', null=True, verbose_name='室外温度')),
                ('ygdn', models.FloatField(blank=True, db_column='有功电能', null=True, verbose_name='有功电能')),
                ('ywssll', models.FloatField(blank=True, db_column='一网瞬时流量', null=True, verbose_name='一网瞬时流量')),
                ('ywljll', models.FloatField(blank=True, db_column='一网累计流量', null=True, verbose_name='一网累计流量')),
                ('bsljll', models.FloatField(blank=True, db_column='补水累积流量', null=True, verbose_name='补水累积流量')),
                ('ywssrl', models.FloatField(blank=True, db_column='一网瞬时热量', null=True, verbose_name='一网瞬时热量')),
                ('ywljrl', models.FloatField(blank=True, db_column='一网累计热量', null=True, verbose_name='一网累计热量')),
                ('ewgw', models.FloatField(blank=True, db_column='二网供温', null=True, verbose_name='二网供温')),
                ('ewhw', models.FloatField(blank=True, db_column='二网回温', null=True, verbose_name='二网回温')),
                ('ewwc', models.FloatField(blank=True, db_column='二网温差', null=True, verbose_name='二网温差')),
                ('egyl', models.FloatField(blank=True, db_column='二供压力', null=True, verbose_name='二供压力')),
                ('ehyl', models.FloatField(blank=True, db_column='二回压力', null=True, verbose_name='二回压力')),
                ('ewyc', models.FloatField(blank=True, db_column='二网压差', null=True, verbose_name='二网压差')),
                ('sxyw', models.FloatField(blank=True, db_column='水箱液位', null=True, verbose_name='水箱液位')),
                ('yhxhbpl', models.FloatField(blank=True, db_column='一号循环泵频率', null=True, verbose_name='一号循环泵频率')),
                ('yhxhbsdpl', models.FloatField(blank=True, db_column='一号循环泵设定频率', null=True, verbose_name='一号循环泵设定频率')),
                ('ehxhbpl', models.FloatField(blank=True, db_column='二号循环泵频率', null=True, verbose_name='二号循环泵频率')),
                ('ehxhbsdpl', models.FloatField(blank=True, db_column='二号循环泵设定频率', null=True, verbose_name='二号循环泵设定频率')),
                ('shxhbsdpl', models.FloatField(blank=True, db_column='三号循环泵设定频率', null=True, verbose_name='三号循环泵设定频率')),
                ('ehbsbpl', models.FloatField(blank=True, db_column='二号补水泵频率', null=True, verbose_name='二号补水泵频率')),
                ('ehbsbsdpl', models.FloatField(blank=True, db_column='二号补水泵设定频率', null=True, verbose_name='二号补水泵设定频率')),
                ('ewssll', models.FloatField(blank=True, db_column='二网瞬时流量', null=True, verbose_name='二网瞬时流量')),
                ('ewljll', models.FloatField(blank=True, db_column='二网累计流量', null=True, verbose_name='二网累计流量')),
                ('ewssrl', models.FloatField(blank=True, db_column='二网瞬时热量', null=True, verbose_name='二网瞬时热量')),
                ('ewljrl', models.FloatField(blank=True, db_column='二网累计热量', null=True, verbose_name='二网累计热量')),
                ('bsssll', models.FloatField(blank=True, db_column='补水瞬时流量', null=True, verbose_name='补水瞬时流量')),
                ('zqmgwd', models.FloatField(blank=True, db_column='蒸汽母管温度', null=True, verbose_name='蒸汽母管温度')),
                ('ljsljll', models.FloatField(blank=True, db_column='凝结水累计流量', null=True, verbose_name='凝结水累计流量')),
                ('ljsssll', models.FloatField(blank=True, db_column='凝结水瞬时流量', null=True, verbose_name='凝结水瞬时流量')),
                ('ljsgwd', models.FloatField(blank=True, db_column='凝结水管温度', null=True, verbose_name='凝结水管温度')),
                ('ljsgyl', models.FloatField(blank=True, db_column='凝结水管压力', null=True, verbose_name='凝结水管压力')),
                ('zqmgyl', models.FloatField(blank=True, db_column='蒸汽母管压力', null=True, verbose_name='蒸汽母管压力')),
                ('shxhbpl', models.FloatField(blank=True, db_column='四号循环泵频率', null=True, verbose_name='四号循环泵频率')),
            ],
            options={
                'verbose_name': '德润产业园换热站地暖区',
                'verbose_name_plural': '德润产业园换热站地暖区',
                'db_table': '德润产业园换热站地暖区',
            },
        ),
    ]
